compatibility_date = "2022-12-26"

[vars]
HCAPTCHA_SITE_KEY = "10000000-ffff-ffff-ffff-000000000001"
USE_CUSTOM_DOMAIN_FOR_IMAGES = false

# Used for email verification: https://verifier.meetchopra.com/
VERIFIER_MEETCHOPRA_KEY=""
MAILERSEND_API_KEY=""

# Cloudflare 
CLOUDFLARE_ACCOUNT_HASH=""
CLOUDFLARE_ACCOUNT_ID=""
# Edit content (KV)
CLOUDFLARE_EDIT_CONTENT_API_TOKEN=""
CLOUDFLARE_CONTENT_KV_NAMESPACE_ID_STAGING=""
CLOUDFLARE_CONTENT_KV_NAMESPACE_ID_PROD=""
# Read,Edit Images API Token
CLOUDFLARE_IMAGES_API_TOKEN=""