name = "dev-mccuna-com"

workers_dev = true
main = "./build/index.js"

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-08-22"

[site]
  bucket = "./public"

[vars]
DSN_URL = "https://d0a8c8d83d0f431eba3183105694384e@o1322298.ingest.sentry.io/6685598"