main = "./dist/worker.mjs"
compatibility_date = "2022-09-01"

[site]
  bucket = "./public"

[build]
watch_dir = "./build"

[env.development]
workers_dev = true
name = "dev"

[env.development.vars]
HCAPTCHA_SITE_KEY = "10000000-ffff-ffff-ffff-000000000001"
CLOUDFLARE_ACCOUNT_HASH = "0uj9SUnHui6vrXgyuOODuw"

[env.staging]
workers_dev = true
name = "staging"

[env.staging.vars]
HCAPTCHA_SITE_KEY = "d1d7c3a9-ad03-470c-bc99-0ba9656f5cc0"
CLOUDFLARE_ACCOUNT_HASH = "0uj9SUnHui6vrXgyuOODuw"

[env.production]
name = "mccuna-com"
route = { pattern = 'https://mccuna.com/*', zone_id = "0c71b410fbbb650642aa7a7c251aa380" }

[env.production.vars]
HCAPTCHA_SITE_KEY = "d1d7c3a9-ad03-470c-bc99-0ba9656f5cc0"
CLOUDFLARE_ACCOUNT_HASH = "0uj9SUnHui6vrXgyuOODuw"
